version: "3.8"

services:
  app:
    container_name: dak-hotel-frontend
    image: dak-hotel-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Kolkata # Set the time zone for the app service
    networks:
      - nodeNETWORK

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - app
    environment:
      - TZ=Asia/Kolkata # Set the time zone for the nginx service
    networks:
      - nodeNETWORK

networks:
  nodeNETWORK:
    external: true
