version: '3.8'

services:
  app:
    container_name: dak-hotel-frontend  # Set the custom container name
    image: dak-hotel-frontend  # Set the custom container name
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map the container's port 3033 to the host
    environment:
      - TZ=Asia/Kolkata
    networks:
      - nodeNETWORK

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    ports:
      - "90:80"
    environment:
      - TZ=Asia/Kolkata
    depends_on:
      - app
    networks:
      - nodeNETWORK

networks:
  nodeNETWORK:
    external: true

