version: "3.9"

services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile-nodejs
    restart: always
    hostname: nodejs-app
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=5001
      - JWT_SECRET=sdlkjfdasnfmouficksdmnciavasdlkacnlk
      - DB_CONNECTION_STR=mongodb+srv://kapildev09994:hellofromtheotherside@serverlessinstance0.6iqsvlf.mongodb.net/dak_hotels?retryWrites=true&w=majority
    networks:
      - nodeNETWORK

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - nodejs-app
    networks:
      - nodeNETWORK

networks:
  nodeNETWORK:
    external: true
